/*
 * AddMedewerker.java
 *
 * Created on 19-jan-2011, 23:20:39
 */
package view;

import connectivity.ShaEncrypt;
import model.Employee;
import roosterprogramma.RoosterProgramma;

/**
 *
 * @author Dymion
 */
public class ChAddEmployee extends javax.swing.JPanel {

    private Employee employee;
    private boolean isAdd = true;

    /** Creates new form AddMedewerker */
    public ChAddEmployee() {
        initComponents();
        lblNameInUse.setVisible(false);
        lblNumberInUse.setVisible(false);
        pnlPartTime.setVisible(false);
        pnlCallWorker.setVisible(false);
        pnlClerk.setVisible(false);
        pnlMuseumEducator.setVisible(false);
    }

    public ChAddEmployee(Employee employee) {
        this.employee = employee;
        this.isAdd = false;
        initComponents();
        fillFields();
        lblNameInUse.setVisible(false);
        lblNumberInUse.setVisible(false);
    }

    private void fillFields() {
        tfEmployeeNumber.setText(Integer.toString(employee.getEmployeeNumber()));
        tfFirstName.setText(employee.getFirstName());
        tfInsertion.setText(employee.getInsertion());
        tfFamilyName.setText(employee.getFamilyName());
        if (employee.isClerk()) {
            cbClerk.setSelected(true);
            pnlMuseumEducator.setVisible(false);
            pnlClerk.setVisible(true);
            pnlPartTime.setVisible(false);
            pnlCallWorker.setVisible(false);
            pnlDays.setVisible(true);
            tfClerk.setText(Double.toString(employee.getContractHours()));
        } else if (employee.isPartTime()) {
            cbPartTime.setSelected(true);
            pnlMuseumEducator.setVisible(false);
            pnlClerk.setVisible(false);
            pnlPartTime.setVisible(true);
            pnlCallWorker.setVisible(false);
            pnlDays.setVisible(false);
            tfPartTime.setText(Double.toString(employee.getContractHours()));
        } else if (employee.isCallWorker()) {
            cbCallWorker.setSelected(true);
            pnlMuseumEducator.setVisible(false);
            pnlClerk.setVisible(false);
            pnlCallWorker.setVisible(true);
            pnlPartTime.setVisible(false);
            pnlDays.setVisible(false);
            tfCallWorker.setText(Double.toString(employee.getContractHours()));
        } else if (employee.isMuseumEducator()) {
            cbMuseumEducator.setSelected(true);
            pnlMuseumEducator.setVisible(true);
            pnlClerk.setVisible(false);
            pnlCallWorker.setVisible(false);
            pnlPartTime.setVisible(false);
            pnlDays.setVisible(false);
            tfMuseumEducator.setText(Double.toString(employee.getContractHours()));
        } else {
            cbFullTime.setSelected(true);
            pnlMuseumEducator.setVisible(false);
            pnlClerk.setVisible(false);
            pnlPartTime.setVisible(false);
            pnlCallWorker.setVisible(false);
            pnlDays.setVisible(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        lblEmployeeNumber = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblFamilyName = new javax.swing.JLabel();
        lblWachtwoord = new javax.swing.JLabel();
        tfEmployeeNumber = new javax.swing.JTextField();
        tfFirstName = new javax.swing.JTextField();
        tfFamilyName = new javax.swing.JTextField();
        lblFullTime = new javax.swing.JLabel();
        cbFullTime = new javax.swing.JCheckBox();
        lblPartTime = new javax.swing.JLabel();
        cbPartTime = new javax.swing.JCheckBox();
        pnlPartTime = new javax.swing.JPanel();
        lblAmountHours = new javax.swing.JLabel();
        tfPartTime = new javax.swing.JTextField();
        lblCallWorker = new javax.swing.JLabel();
        cbCallWorker = new javax.swing.JCheckBox();
        pnlCallWorker = new javax.swing.JPanel();
        lblMinAmountHours = new javax.swing.JLabel();
        tfCallWorker = new javax.swing.JTextField();
        lblClerk = new javax.swing.JLabel();
        cbClerk = new javax.swing.JCheckBox();
        pnlClerk = new javax.swing.JPanel();
        tfClerk = new javax.swing.JTextField();
        lblMinAmountHours1 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        tfPassword = new javax.swing.JPasswordField();
        lblNameInUse = new javax.swing.JLabel();
        lblNumberInUse = new javax.swing.JLabel();
        pnlDays = new javax.swing.JPanel();
        lblMonday = new javax.swing.JLabel();
        lblTuesday = new javax.swing.JLabel();
        lblWednesday = new javax.swing.JLabel();
        lblThursday = new javax.swing.JLabel();
        lblFriday = new javax.swing.JLabel();
        lblSaturday = new javax.swing.JLabel();
        Sunday = new javax.swing.JLabel();
        cbThursday = new javax.swing.JCheckBox();
        cbWednesday = new javax.swing.JCheckBox();
        cbTuesday = new javax.swing.JCheckBox();
        cbMonday = new javax.swing.JCheckBox();
        cbFriday = new javax.swing.JCheckBox();
        cbSaturday = new javax.swing.JCheckBox();
        cbSunday = new javax.swing.JCheckBox();
        lblInstruction = new javax.swing.JLabel();
        cbMuseumEducator = new javax.swing.JCheckBox();
        lblMuseumEducator = new javax.swing.JLabel();
        pnlMuseumEducator = new javax.swing.JPanel();
        lblMinAmountHours2 = new javax.swing.JLabel();
        tfMuseumEducator = new javax.swing.JTextField();
        lblInsertion = new javax.swing.JLabel();
        tfInsertion = new javax.swing.JTextField();

        lblEmployeeNumber.setText("PersoneelsNummer:");

        lblFirstName.setText("Voornaam:");

        lblFamilyName.setText("Achternaam:");

        lblWachtwoord.setText("Wachtwoord:");

        tfEmployeeNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfEmployeeNumberKeyReleased(evt);
            }
        });

        tfFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfFirstNameKeyReleased(evt);
            }
        });

        tfFamilyName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfFamilyNameKeyReleased(evt);
            }
        });

        lblFullTime.setText("Fulltime:");

        buttonGroup.add(cbFullTime);
        cbFullTime.setSelected(true);
        cbFullTime.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbFullTimeStateChanged(evt);
            }
        });

        lblPartTime.setText("Parttime:");

        buttonGroup.add(cbPartTime);
        cbPartTime.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbPartTimeStateChanged(evt);
            }
        });

        lblAmountHours.setText("Aantal uur per week:");

        tfPartTime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPartTimeKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlPartTimeLayout = new javax.swing.GroupLayout(pnlPartTime);
        pnlPartTime.setLayout(pnlPartTimeLayout);
        pnlPartTimeLayout.setHorizontalGroup(
            pnlPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPartTimeLayout.createSequentialGroup()
                .addComponent(lblAmountHours)
                .addGap(89, 89, 89)
                .addComponent(tfPartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(815, Short.MAX_VALUE))
        );
        pnlPartTimeLayout.setVerticalGroup(
            pnlPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblAmountHours, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tfPartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblCallWorker.setText("Oproepkracht:");

        buttonGroup.add(cbCallWorker);
        cbCallWorker.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbCallWorkerStateChanged(evt);
            }
        });

        lblMinAmountHours.setText("Minimum aantal uur per week:");

        tfCallWorker.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCallWorkerKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlCallWorkerLayout = new javax.swing.GroupLayout(pnlCallWorker);
        pnlCallWorker.setLayout(pnlCallWorkerLayout);
        pnlCallWorkerLayout.setHorizontalGroup(
            pnlCallWorkerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCallWorkerLayout.createSequentialGroup()
                .addComponent(lblMinAmountHours)
                .addGap(47, 47, 47)
                .addComponent(tfCallWorker, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(815, Short.MAX_VALUE))
        );
        pnlCallWorkerLayout.setVerticalGroup(
            pnlCallWorkerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCallWorkerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblMinAmountHours, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tfCallWorker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblClerk.setText("Baliemedewerker:");

        buttonGroup.add(cbClerk);
        cbClerk.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbClerkStateChanged(evt);
            }
        });

        tfClerk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfClerkKeyReleased(evt);
            }
        });

        lblMinAmountHours1.setText("Minimum aantal uur per week:");

        javax.swing.GroupLayout pnlClerkLayout = new javax.swing.GroupLayout(pnlClerk);
        pnlClerk.setLayout(pnlClerkLayout);
        pnlClerkLayout.setHorizontalGroup(
            pnlClerkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClerkLayout.createSequentialGroup()
                .addComponent(lblMinAmountHours1)
                .addGap(46, 46, 46)
                .addComponent(tfClerk, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(813, Short.MAX_VALUE))
        );
        pnlClerkLayout.setVerticalGroup(
            pnlClerkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClerkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblMinAmountHours1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tfClerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnCancel.setText("Annuleren");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setText("Opslaan");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        tfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPasswordKeyReleased(evt);
            }
        });

        lblNameInUse.setText("De combinatie voor- en achternaam is al in gebruik!");

        lblNumberInUse.setText("Dat nummer is al in gebruik!");

        lblMonday.setText("Maandag");

        lblTuesday.setText("Dinsdag");

        lblWednesday.setText("Woensdag");

        lblThursday.setText("Donderdag");

        lblFriday.setText("Vrijdag");

        lblSaturday.setText("Zaterdag");

        Sunday.setText("Zondag");

        lblInstruction.setText("Niet in te roosteren dagen");

        javax.swing.GroupLayout pnlDaysLayout = new javax.swing.GroupLayout(pnlDays);
        pnlDays.setLayout(pnlDaysLayout);
        pnlDaysLayout.setHorizontalGroup(
            pnlDaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDaysLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDaysLayout.createSequentialGroup()
                        .addGroup(pnlDaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblThursday)
                            .addComponent(lblWednesday)
                            .addComponent(lblTuesday)
                            .addComponent(lblMonday)
                            .addComponent(lblFriday)
                            .addComponent(lblSaturday)
                            .addComponent(Sunday))
                        .addGap(18, 18, 18)
                        .addGroup(pnlDaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbSunday)
                            .addComponent(cbSaturday)
                            .addComponent(cbFriday)
                            .addComponent(cbMonday)
                            .addComponent(cbTuesday)
                            .addComponent(cbWednesday)
                            .addComponent(cbThursday)))
                    .addComponent(lblInstruction))
                .addContainerGap(356, Short.MAX_VALUE))
        );
        pnlDaysLayout.setVerticalGroup(
            pnlDaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDaysLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInstruction)
                .addGap(18, 18, 18)
                .addGroup(pnlDaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMonday)
                    .addComponent(cbMonday))
                .addGap(18, 18, 18)
                .addGroup(pnlDaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTuesday)
                    .addComponent(cbTuesday))
                .addGap(18, 18, 18)
                .addGroup(pnlDaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWednesday)
                    .addComponent(cbWednesday))
                .addGap(18, 18, 18)
                .addGroup(pnlDaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblThursday)
                    .addComponent(cbThursday))
                .addGap(18, 18, 18)
                .addGroup(pnlDaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFriday)
                    .addComponent(cbFriday))
                .addGap(18, 18, 18)
                .addGroup(pnlDaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaturday)
                    .addComponent(cbSaturday))
                .addGap(18, 18, 18)
                .addGroup(pnlDaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sunday)
                    .addComponent(cbSunday))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroup.add(cbMuseumEducator);
        cbMuseumEducator.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbMuseumEducatorStateChanged(evt);
            }
        });

        lblMuseumEducator.setText("Museumdocent:");

        lblMinAmountHours2.setText("Minimum aantal uur per week:");

        tfMuseumEducator.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfMuseumEducatorKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlMuseumEducatorLayout = new javax.swing.GroupLayout(pnlMuseumEducator);
        pnlMuseumEducator.setLayout(pnlMuseumEducatorLayout);
        pnlMuseumEducatorLayout.setHorizontalGroup(
            pnlMuseumEducatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMuseumEducatorLayout.createSequentialGroup()
                .addComponent(lblMinAmountHours2)
                .addGap(46, 46, 46)
                .addComponent(tfMuseumEducator, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(815, Short.MAX_VALUE))
        );
        pnlMuseumEducatorLayout.setVerticalGroup(
            pnlMuseumEducatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMuseumEducatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblMinAmountHours2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tfMuseumEducator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblInsertion.setText("Tussenvoegsel:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnCancel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1062, Short.MAX_VALUE)
                                    .addComponent(btnSave))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblEmployeeNumber)
                                                .addComponent(lblFirstName))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(tfFirstName, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfEmployeeNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                                                .addComponent(tfInsertion, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfFamilyName, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfPassword, javax.swing.GroupLayout.Alignment.LEADING)))
                                        .addComponent(lblFamilyName)
                                        .addComponent(lblWachtwoord))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNumberInUse)
                                        .addComponent(lblNameInUse))
                                    .addGap(496, 496, 496)))
                            .addGap(10, 10, 10))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblInsertion)
                            .addContainerGap(1149, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblMuseumEducator)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblClerk)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblPartTime)
                                        .addComponent(lblFullTime)
                                        .addComponent(lblCallWorker))
                                    .addGap(14, 14, 14)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cbCallWorker)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbFullTime)
                                            .addComponent(cbPartTime))
                                        .addComponent(cbMuseumEducator)
                                        .addComponent(cbClerk))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pnlClerk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pnlCallWorker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pnlPartTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pnlMuseumEducator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGap(4, 4, 4)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeNumber)
                    .addComponent(tfEmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumberInUse))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(tfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInsertion)
                    .addComponent(tfInsertion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFamilyName)
                    .addComponent(tfFamilyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameInUse))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWachtwoord)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblFullTime)
                        .addGap(25, 25, 25)
                        .addComponent(lblPartTime))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cbFullTime)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlPartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbPartTime))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbCallWorker)
                    .addComponent(lblCallWorker)
                    .addComponent(pnlCallWorker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMuseumEducator)
                    .addComponent(cbMuseumEducator)
                    .addComponent(pnlMuseumEducator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblClerk)
                    .addComponent(cbClerk)
                    .addComponent(pnlClerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnlDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        RoosterProgramma.getInstance().showPanel(new EmployeeOverview());
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        int employeeNumber = Integer.parseInt(tfEmployeeNumber.getText());
        String firstName = tfFirstName.getText();
        String insertion = tfInsertion.getText();
        String familyName = tfFamilyName.getText();
        String password = RoosterProgramma.getInstance().decodePassword(tfPassword.getPassword());
        boolean fullTime = cbFullTime.isSelected();
        boolean partTime = cbPartTime.isSelected();
        boolean callWorker = cbCallWorker.isSelected();
        boolean clerk = cbClerk.isSelected();

        // ToDo: Cleanup, dit kan mooier XD

        if (isAdd) {
            Employee newEmployee = new Employee();
            newEmployee.setEmployeeNumber(employeeNumber);
            newEmployee.setFirstName(firstName);
            newEmployee.setInsertion(insertion);
            newEmployee.setFamilyName(familyName);
            newEmployee.setPassword(ShaEncrypt.SHA1(password));
            newEmployee.setFullTime(fullTime);
            newEmployee.setPartTime(partTime);
            newEmployee.setCallWorker(callWorker);
            newEmployee.setClerk(clerk);
            if (newEmployee.isCallWorker()) {
                newEmployee.setContractHours(Double.parseDouble(tfCallWorker.getText()));
            } else if (newEmployee.isPartTime()) {
                newEmployee.setContractHours(Double.parseDouble(tfPartTime.getText()));
            } else if (newEmployee.isFullTime()) {
                newEmployee.setContractHours(40);
            } else if (newEmployee.isClerk()) {
                newEmployee.setContractHours(Double.parseDouble(tfClerk.getText()));
            } else if (newEmployee.isMuseumEducator()) {
                newEmployee.setContractHours(Double.parseDouble(tfMuseumEducator.getText()));
            }
            RoosterProgramma.getQueryManager().addEmployee(newEmployee);
        } else {
            employee.setFirstName(firstName);
            employee.setInsertion(insertion);
            employee.setFamilyName(familyName);
            employee.setPassword(ShaEncrypt.SHA1(password));
            employee.setFullTime(fullTime);
            employee.setPartTime(partTime);
            employee.setCallWorker(callWorker);
            employee.setClerk(clerk);
            if (employee.isCallWorker()) {
                employee.setContractHours(Double.parseDouble(tfCallWorker.getText()));
            } else if (employee.isPartTime()) {
                employee.setContractHours(Double.parseDouble(tfPartTime.getText()));
            } else if (employee.isFullTime()) {
                employee.setContractHours(40);
            } else if (employee.isClerk()) {
                employee.setContractHours(Double.parseDouble(tfClerk.getText()));
            } else if (employee.isMuseumEducator()) {
                employee.setContractHours(Double.parseDouble(tfMuseumEducator.getText()));
            }
            employee.update();
        }
        RoosterProgramma.getInstance().showPanel(new EmployeeOverview());

    }//GEN-LAST:event_btnSaveActionPerformed

    private void tfEmployeeNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfEmployeeNumberKeyReleased
        checkEnabled();
    }//GEN-LAST:event_tfEmployeeNumberKeyReleased

    private void tfFirstNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFirstNameKeyReleased
        checkEnabled();
    }//GEN-LAST:event_tfFirstNameKeyReleased

    private void tfFamilyNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFamilyNameKeyReleased
        checkEnabled();
    }//GEN-LAST:event_tfFamilyNameKeyReleased

    private void tfPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPasswordKeyReleased
        checkEnabled();
    }//GEN-LAST:event_tfPasswordKeyReleased

    private void cbFullTimeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbFullTimeStateChanged
        checkEnabled();
    }//GEN-LAST:event_cbFullTimeStateChanged

    private void cbPartTimeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbPartTimeStateChanged
        checkEnabled();
        if (cbPartTime.isSelected()) {
            pnlPartTime.setVisible(true);
        } else {
            pnlPartTime.setVisible(false);
        }
    }//GEN-LAST:event_cbPartTimeStateChanged

    private void cbCallWorkerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbCallWorkerStateChanged
        checkEnabled();
        if (cbCallWorker.isSelected()) {
            pnlCallWorker.setVisible(true);
        } else {
            pnlCallWorker.setVisible(false);
        }
    }//GEN-LAST:event_cbCallWorkerStateChanged

    private void tfPartTimeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPartTimeKeyReleased
        checkEnabled();
    }//GEN-LAST:event_tfPartTimeKeyReleased

    private void tfCallWorkerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCallWorkerKeyReleased
        checkEnabled();
    }//GEN-LAST:event_tfCallWorkerKeyReleased

    private void cbClerkStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbClerkStateChanged
        checkEnabled();
        if (cbClerk.isSelected()) {
            pnlClerk.setVisible(true);
            pnlDays.setVisible(true);
        } else {
            pnlClerk.setVisible(false);
            pnlDays.setVisible(false);
        }
    }//GEN-LAST:event_cbClerkStateChanged

    private void tfClerkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfClerkKeyReleased
        checkEnabled();
    }//GEN-LAST:event_tfClerkKeyReleased

    private void cbMuseumEducatorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbMuseumEducatorStateChanged
        checkEnabled();
        if (cbMuseumEducator.isSelected()) {
            pnlMuseumEducator.setVisible(true);
        } else {
            pnlMuseumEducator.setVisible(false);
        }
    }//GEN-LAST:event_cbMuseumEducatorStateChanged

    private void tfMuseumEducatorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMuseumEducatorKeyReleased
        checkEnabled();
    }//GEN-LAST:event_tfMuseumEducatorKeyReleased

    private void checkEnabled() {
        if (!tfEmployeeNumber.getText().isEmpty()
                && RoosterProgramma.getInstance().isNumeric(tfEmployeeNumber.getText())
                && !tfFirstName.getText().isEmpty()
                && !tfFamilyName.getText().isEmpty()
                && !Exist()
                && !RoosterProgramma.getInstance().decodePassword(tfPassword.getPassword()).isEmpty()
                && (cbFullTime.isSelected()
                || (cbPartTime.isSelected() && !tfPartTime.getText().isEmpty() && RoosterProgramma.getInstance().isNumeric(tfPartTime.getText()))
                || (cbCallWorker.isSelected() && !tfCallWorker.getText().isEmpty() && RoosterProgramma.getInstance().isNumeric(tfCallWorker.getText()))
                || (cbMuseumEducator.isSelected() && !tfMuseumEducator.getText().isEmpty() && RoosterProgramma.getInstance().isNumeric(tfMuseumEducator.getText()))
                || (cbClerk.isSelected() && !tfClerk.getText().isEmpty() && RoosterProgramma.getInstance().isNumeric(tfClerk.getText())))) {
            btnSave.setEnabled(true);
        } else {
            btnSave.setEnabled(false);
        }
    }

    private boolean Exist() {
        int employeeNumber = Integer.parseInt(tfEmployeeNumber.getText());
        String familyName = tfFamilyName.getText().toLowerCase();
        String firstName = tfFirstName.getText().toLowerCase();
        boolean exists = false;
        for (Employee existingEmployee : RoosterProgramma.getQueryManager().getEmployees()) {
            if (existingEmployee.getEmployeeNumber() == employeeNumber
                    && (isAdd || employee.getEmployeeNumber() != employeeNumber)) {   // If number is in use
                lblNameInUse.setVisible(false);
                exists = true;
                lblNumberInUse.setVisible(true);
            } else if (existingEmployee.getFamilyName().toLowerCase().equals(familyName) && existingEmployee.getFirstName().toLowerCase().equals(firstName)
                    && (isAdd || (!employee.getFirstName().toLowerCase().equals(firstName) || !employee.getFamilyName().toLowerCase().equals(familyName)))) {   // If name is in use
                lblNumberInUse.setVisible(false);
                exists = true;
                lblNameInUse.setVisible(true);
            } else {
                lblNameInUse.setVisible(false);
                lblNumberInUse.setVisible(false);
            }
            if (exists) {
                return true;
            }
        }
        return false;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Sunday;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbCallWorker;
    private javax.swing.JCheckBox cbClerk;
    private javax.swing.JCheckBox cbFriday;
    private javax.swing.JCheckBox cbFullTime;
    private javax.swing.JCheckBox cbMonday;
    private javax.swing.JCheckBox cbMuseumEducator;
    private javax.swing.JCheckBox cbPartTime;
    private javax.swing.JCheckBox cbSaturday;
    private javax.swing.JCheckBox cbSunday;
    private javax.swing.JCheckBox cbThursday;
    private javax.swing.JCheckBox cbTuesday;
    private javax.swing.JCheckBox cbWednesday;
    private javax.swing.JLabel lblAmountHours;
    private javax.swing.JLabel lblCallWorker;
    private javax.swing.JLabel lblClerk;
    private javax.swing.JLabel lblEmployeeNumber;
    private javax.swing.JLabel lblFamilyName;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblFriday;
    private javax.swing.JLabel lblFullTime;
    private javax.swing.JLabel lblInsertion;
    private javax.swing.JLabel lblInstruction;
    private javax.swing.JLabel lblMinAmountHours;
    private javax.swing.JLabel lblMinAmountHours1;
    private javax.swing.JLabel lblMinAmountHours2;
    private javax.swing.JLabel lblMonday;
    private javax.swing.JLabel lblMuseumEducator;
    private javax.swing.JLabel lblNameInUse;
    private javax.swing.JLabel lblNumberInUse;
    private javax.swing.JLabel lblPartTime;
    private javax.swing.JLabel lblSaturday;
    private javax.swing.JLabel lblThursday;
    private javax.swing.JLabel lblTuesday;
    private javax.swing.JLabel lblWachtwoord;
    private javax.swing.JLabel lblWednesday;
    private javax.swing.JPanel pnlCallWorker;
    private javax.swing.JPanel pnlClerk;
    private javax.swing.JPanel pnlDays;
    private javax.swing.JPanel pnlMuseumEducator;
    private javax.swing.JPanel pnlPartTime;
    private javax.swing.JTextField tfCallWorker;
    private javax.swing.JTextField tfClerk;
    private javax.swing.JTextField tfEmployeeNumber;
    private javax.swing.JTextField tfFamilyName;
    private javax.swing.JTextField tfFirstName;
    private javax.swing.JTextField tfInsertion;
    private javax.swing.JTextField tfMuseumEducator;
    private javax.swing.JTextField tfPartTime;
    private javax.swing.JPasswordField tfPassword;
    // End of variables declaration//GEN-END:variables
}
