/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MakeAccount.java
 *
 * Created on 27-nov-2010, 16:43:51
 */

package view;

import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import main.ServerManager;

/**
 *
 * @author Dark
 */
public class MakeAccount extends javax.swing.JPanel {

    /** Creates new form MakeAccount */
    public MakeAccount() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfPass = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cbGMTest = new javax.swing.JComboBox();
        cbAddon = new javax.swing.JComboBox();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Name :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jPanel1.add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 110, -1));

        jLabel2.setText("Password :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        jPanel1.add(tfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 110, -1));

        jLabel3.setText("Gmlevel :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel4.setText("Addon :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jButton1.setText("Create!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 180, 40));

        cbGMTest.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3" }));
        cbGMTest.setSelectedIndex(0);
        jPanel1.add(cbGMTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 60, -1));
        cbGMTest.getAccessibleContext().setAccessibleName("null");

        cbAddon.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vanilla", "TBC", "WotLK" }));
        cbAddon.setSelectedIndex(2);
        jPanel1.add(cbAddon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Name");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Name = tfName.getText();
        String Pass = tfPass.getText();
        String GmlevelValue = (String) cbGMTest.getSelectedItem();
        int Gmlevel = Integer.parseInt(GmlevelValue);
        int Addon = cbAddon.getSelectedIndex();
        try
        {
            ServerManager.getQueryManager().makeAccount(Name, Pass, Gmlevel, Addon);
            JOptionPane.showMessageDialog(null, "Account has been created");
            tfName.setText("");
            tfPass.setText("");
            cbGMTest.setSelectedIndex(0);
            cbAddon.setSelectedIndex(2);
        } 
        catch (NoSuchAlgorithmException ex)
        {
            Logger.getLogger(MakeAccount.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (UnsupportedEncodingException ex)
        {
            Logger.getLogger(MakeAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbAddon;
    private javax.swing.JComboBox cbGMTest;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPass;
    // End of variables declaration//GEN-END:variables

}
