alter table `roosterprogramma`.`werktijden` 
   change `Margo Aarsen` `Margo Aarsen` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Brechje Manden` `Brechje Manden` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Annie de Boer` `Annie de Boer` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Miriam Blokker` `Miriam Blokker` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Toyah Boot` `Toyah Boot` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Paulien Bosman` `Paulien Bosman` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Annemijn Bouwman` `Annemijn Bouwman` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Inge Commandeur` `Inge Commandeur` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Wiepke Draisma` `Wiepke Draisma` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Farida Guseynova` `Farida Guseynova` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Gerard Horneman` `Gerard Horneman` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Rita Hooijschuur` `Rita Hooijschuur` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Florence van Heuvelen` `Florence van Heuvelen` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Lia Kijzer` `Lia Kijzer` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Anneke Leeuw` `Anneke Leeuw` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Antonio Lopes` `Antonio Lopes` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Nathalie Louter` `Nathalie Louter` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Meta Lepelaar` `Meta Lepelaar` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Maaike Teunissen` `Maaike Teunissen` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Noortje Molenaar` `Noortje Molenaar` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Ananda Marchildon` `Ananda Marchildon` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Ilse Moester` `Ilse Moester` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Els Neeft` `Els Neeft` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Mandy Ploeger` `Mandy Ploeger` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Fokelien Renckens` `Fokelien Renckens` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Jacqueline Jonker` `Jacqueline Jonker` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Eva Rijs` `Eva Rijs` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Kiona van Rooijen` `Kiona van Rooijen` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Femke Stevens` `Femke Stevens` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Marieke Tervoort` `Marieke Tervoort` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `José Tijhuis` `José Tijhuis` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Ellen Timmer` `Ellen Timmer` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Jolanda Vries` `Jolanda Vries` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Remco de Vries` `Remco de Vries` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Petra Dol` `Petra Dol` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Els Vermeijden` `Els Vermeijden` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Hester Wandel` `Hester Wandel` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Daantje van de Weijer` `Daantje van de Weijer` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Marieke Roggeveen` `Marieke Roggeveen` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Yvonne Zwart` `Yvonne Zwart` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Rena Zendedel` `Rena Zendedel` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL, 
   change `Chengiz Zendedel` `Chengiz Zendedel` varchar(255) character set latin1 collate latin1_swedish_ci default '0;0;0;0;0;0;0;0;0' NOT NULL;