/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddMedewerker.java
 *
 * Created on 19-jan-2011, 23:20:39
 */

package view;

import java.util.ArrayList;
import java.util.List;
import model.Employee;
import roosterprogramma.RoosterProgramma;

/**
 *
 * @author Dymion
 */
public class AddMedewerker extends javax.swing.JPanel {

    /** Creates new form AddMedewerker */
    public AddMedewerker() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPersoneelNr = new javax.swing.JLabel();
        lblVoornaam = new javax.swing.JLabel();
        lblAchternaam = new javax.swing.JLabel();
        lblWachtwoord = new javax.swing.JLabel();
        lblFulltime = new javax.swing.JLabel();
        lblParttime = new javax.swing.JLabel();
        lblOproepkracht = new javax.swing.JLabel();
        tfPersoneelsNr = new javax.swing.JTextField();
        tfVoornaam = new javax.swing.JTextField();
        tfAchternaam = new javax.swing.JTextField();
        tfWachtwoord = new javax.swing.JTextField();
        cbFulltime = new javax.swing.JCheckBox();
        cbParttime = new javax.swing.JCheckBox();
        cbOproepkracht = new javax.swing.JCheckBox();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        lblPersoneelNr.setText("PersoneelsNummer:");

        lblVoornaam.setText("Voornaam:");

        lblAchternaam.setText("Achternaam:");

        lblWachtwoord.setText("Wachtwoord:");

        lblFulltime.setText("Fulltime:");

        lblParttime.setText("Parttime:");

        lblOproepkracht.setText("Oproepkracht:");

        tfAchternaam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAchternaamActionPerformed(evt);
            }
        });

        btnCancel.setText("Annuleren");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setText("Opslaan");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPersoneelNr)
                            .addComponent(lblVoornaam)
                            .addComponent(lblAchternaam)
                            .addComponent(lblWachtwoord)
                            .addComponent(lblFulltime)
                            .addComponent(lblParttime)
                            .addComponent(lblOproepkracht))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbOproepkracht)
                            .addComponent(cbParttime)
                            .addComponent(cbFulltime)
                            .addComponent(tfPersoneelsNr, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(tfVoornaam)
                            .addComponent(tfAchternaam)
                            .addComponent(tfWachtwoord)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 435, Short.MAX_VALUE)
                        .addComponent(btnSave)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPersoneelNr)
                    .addComponent(tfPersoneelsNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVoornaam)
                    .addComponent(tfVoornaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAchternaam)
                    .addComponent(tfAchternaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWachtwoord)
                    .addComponent(tfWachtwoord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFulltime)
                    .addComponent(cbFulltime))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblParttime)
                    .addComponent(cbParttime))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOproepkracht)
                    .addComponent(cbOproepkracht))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfAchternaamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAchternaamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAchternaamActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        RoosterProgramma.getInstance().showPanel(new medewerkerOverzicht());
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        int personeelNr = Integer.parseInt(tfPersoneelsNr.getText());
        String voornaam = tfVoornaam.getText();
        String achternaam = tfAchternaam.getText();
        String wachtwoord = tfWachtwoord.getText();
        boolean fulltime = cbFulltime.isSelected();
        boolean parttime = cbParttime.isSelected();
        boolean oproepkracht = cbOproepkracht.isSelected();

        Employee newemployee = new Employee();
        newemployee.setPersoneelsNummer(personeelNr);
        newemployee.setVoornaam(voornaam);
        newemployee.setAchternaam(achternaam);
        newemployee.setWachtwoord(wachtwoord);
        newemployee.setFulltime(fulltime);
        newemployee.setParttime(parttime);
        newemployee.setOproepkracht(oproepkracht);
        RoosterProgramma.getQueryManager().addEmployee(newemployee);
        RoosterProgramma.getInstance().showPanel(new medewerkerOverzicht());
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox cbFulltime;
    private javax.swing.JCheckBox cbOproepkracht;
    private javax.swing.JCheckBox cbParttime;
    private javax.swing.JLabel lblAchternaam;
    private javax.swing.JLabel lblFulltime;
    private javax.swing.JLabel lblOproepkracht;
    private javax.swing.JLabel lblParttime;
    private javax.swing.JLabel lblPersoneelNr;
    private javax.swing.JLabel lblVoornaam;
    private javax.swing.JLabel lblWachtwoord;
    private javax.swing.JTextField tfAchternaam;
    private javax.swing.JTextField tfPersoneelsNr;
    private javax.swing.JTextField tfVoornaam;
    private javax.swing.JTextField tfWachtwoord;
    // End of variables declaration//GEN-END:variables

}
