/*
 * AddMedewerker.java
 *
 * Created on 19-jan-2011, 23:20:39
 */

package view;

import connectivity.ShaEncrypt;
import model.Employee;
import roosterprogramma.RoosterProgramma;

/**
 *
 * @author Dymion
 */
public class ChAddEmployee extends javax.swing.JPanel {

    private Employee employee;
    private boolean isAdd = true;

    /** Creates new form AddMedewerker */
    public ChAddEmployee() {
        initComponents();
        lblNameInUse.setVisible(false);
        lblNumberInUse.setVisible(false);
    }

    public ChAddEmployee(Employee employee) {
        this.employee = employee;
        this.isAdd = false;
        initComponents();
        fillFields();
        lblNameInUse.setVisible(false);
        lblNumberInUse.setVisible(false);
    }

    private void fillFields() {
        tfEmployeeNumber.setText(Integer.toString(employee.getEmployeeNumber()));
        tfFirstName.setText(employee.getFirstName());
        tfFamilyName.setText(employee.getFamilyName());
        cbFullTime.setSelected(employee.isFullTime());
        cbPartTime.setSelected(employee.isPartTime());
        cbCallWorker.setSelected(employee.isCallWorker());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmployeeNumber = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblFamilyName = new javax.swing.JLabel();
        lblWachtwoord = new javax.swing.JLabel();
        lblFullTime = new javax.swing.JLabel();
        lblPartTime = new javax.swing.JLabel();
        lblCallWorker = new javax.swing.JLabel();
        tfEmployeeNumber = new javax.swing.JTextField();
        tfFirstName = new javax.swing.JTextField();
        tfFamilyName = new javax.swing.JTextField();
        cbFullTime = new javax.swing.JCheckBox();
        cbPartTime = new javax.swing.JCheckBox();
        cbCallWorker = new javax.swing.JCheckBox();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        tfPassword = new javax.swing.JPasswordField();
        lblNameInUse = new javax.swing.JLabel();
        lblNumberInUse = new javax.swing.JLabel();

        lblEmployeeNumber.setText("PersoneelsNummer:");

        lblFirstName.setText("Voornaam:");

        lblFamilyName.setText("Achternaam:");

        lblWachtwoord.setText("Wachtwoord:");

        lblFullTime.setText("Fulltime:");

        lblPartTime.setText("Parttime:");

        lblCallWorker.setText("Oproepkracht:");

        tfEmployeeNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfEmployeeNumberKeyReleased(evt);
            }
        });

        tfFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfFirstNameKeyReleased(evt);
            }
        });

        tfFamilyName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfFamilyNameKeyReleased(evt);
            }
        });

        cbFullTime.setSelected(true);
        cbFullTime.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbFullTimeStateChanged(evt);
            }
        });

        cbPartTime.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbPartTimeStateChanged(evt);
            }
        });

        cbCallWorker.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbCallWorkerStateChanged(evt);
            }
        });

        btnCancel.setText("Annuleren");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setText("Opslaan");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        tfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPasswordKeyReleased(evt);
            }
        });

        lblNameInUse.setText("De combinatie voor- en achternaam is al in gebruik!");

        lblNumberInUse.setText("Dat nummer is al in gebruik!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmployeeNumber)
                            .addComponent(lblFirstName)
                            .addComponent(lblFamilyName)
                            .addComponent(lblWachtwoord)
                            .addComponent(lblFullTime)
                            .addComponent(lblPartTime)
                            .addComponent(lblCallWorker))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfPassword)
                            .addComponent(cbCallWorker)
                            .addComponent(cbPartTime)
                            .addComponent(cbFullTime)
                            .addComponent(tfEmployeeNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(tfFirstName)
                            .addComponent(tfFamilyName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumberInUse)
                            .addComponent(lblNameInUse)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 435, Short.MAX_VALUE)
                        .addComponent(btnSave)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeNumber)
                    .addComponent(tfEmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumberInUse))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(tfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFamilyName)
                    .addComponent(tfFamilyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameInUse))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWachtwoord)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFullTime)
                    .addComponent(cbFullTime))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPartTime)
                    .addComponent(cbPartTime))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCallWorker)
                    .addComponent(cbCallWorker))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        RoosterProgramma.getInstance().showPanel(new EmployeeOverview());
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        int employeeNumber = Integer.parseInt(tfEmployeeNumber.getText());
        String firstName = tfFirstName.getText();
        String familyName = tfFamilyName.getText();
        String password = RoosterProgramma.getInstance().decodePassword(tfPassword.getPassword());
        boolean fullTime = cbFullTime.isSelected();
        boolean partTime = cbPartTime.isSelected();
        boolean callWorker = cbCallWorker.isSelected();

        if (isAdd)
        {
            Employee newEmployee = new Employee();
            newEmployee.setEmployeeNumber(employeeNumber);
            newEmployee.setFirstName(firstName);
            newEmployee.setFamilyName(familyName);
            newEmployee.setPassword(ShaEncrypt.SHA1(password));
            newEmployee.setFullTime(fullTime);
            newEmployee.setPartTime(partTime);
            newEmployee.setCallWorker(callWorker);
            RoosterProgramma.getQueryManager().addEmployee(newEmployee);
        }
        else
        {
            employee.setFirstName(firstName);
            employee.setFamilyName(familyName);
            employee.setPassword(ShaEncrypt.SHA1(password));
            employee.setFullTime(fullTime);
            employee.setPartTime(partTime);
            employee.setCallWorker(callWorker);
            RoosterProgramma.getQueryManager().changeEmployee(employee);
        }
        RoosterProgramma.getInstance().showPanel(new EmployeeOverview());
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tfEmployeeNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfEmployeeNumberKeyReleased
        checkEnabled();
    }//GEN-LAST:event_tfEmployeeNumberKeyReleased

    private void tfFirstNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFirstNameKeyReleased
        checkEnabled();
    }//GEN-LAST:event_tfFirstNameKeyReleased

    private void tfFamilyNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFamilyNameKeyReleased
        checkEnabled();
    }//GEN-LAST:event_tfFamilyNameKeyReleased

    private void tfPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPasswordKeyReleased
        checkEnabled();
    }//GEN-LAST:event_tfPasswordKeyReleased

    private void cbFullTimeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbFullTimeStateChanged
        checkEnabled();
    }//GEN-LAST:event_cbFullTimeStateChanged

    private void cbPartTimeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbPartTimeStateChanged
        checkEnabled();
    }//GEN-LAST:event_cbPartTimeStateChanged

    private void cbCallWorkerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbCallWorkerStateChanged
        checkEnabled();
    }//GEN-LAST:event_cbCallWorkerStateChanged

    private void checkEnabled() {
        if (!tfEmployeeNumber.getText().isEmpty() &&
            !tfFirstName.getText().isEmpty() &&
            !tfFamilyName.getText().isEmpty() &&
            !Exist() &&
            !RoosterProgramma.getInstance().decodePassword(tfPassword.getPassword()).isEmpty() &&
            (cbFullTime.isSelected() || cbPartTime.isSelected() || cbCallWorker.isSelected()))
        {
            btnSave.setEnabled(true);
        }
        else
        {
            btnSave.setEnabled(false);
        }
    }

    private boolean Exist() {
        int employeeNumber = Integer.parseInt(tfEmployeeNumber.getText());
        String familyName = tfFamilyName.getText().toLowerCase();
        String firstName = tfFirstName.getText().toLowerCase();
        boolean exists = false;
        for (Employee existingEmployee : RoosterProgramma.getQueryManager().getEmployees())
        {
            if (!isAdd && existingEmployee.getEmployeeNumber() == employeeNumber)
            {
                lblNameInUse.setVisible(false);
                exists = true;
                lblNumberInUse.setVisible(true);
            }
            else if(!isAdd && (existingEmployee.getFamilyName().toLowerCase().equals(familyName) && existingEmployee.getFirstName().toLowerCase().equals(firstName)))
            {
                lblNumberInUse.setVisible(false);
                exists = true;
                lblNameInUse.setVisible(true);
            }
            else
            {
                lblNameInUse.setVisible(false);
                lblNumberInUse.setVisible(false);
            }
        }
        return exists;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox cbCallWorker;
    private javax.swing.JCheckBox cbFullTime;
    private javax.swing.JCheckBox cbPartTime;
    private javax.swing.JLabel lblCallWorker;
    private javax.swing.JLabel lblEmployeeNumber;
    private javax.swing.JLabel lblFamilyName;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblFullTime;
    private javax.swing.JLabel lblNameInUse;
    private javax.swing.JLabel lblNumberInUse;
    private javax.swing.JLabel lblPartTime;
    private javax.swing.JLabel lblWachtwoord;
    private javax.swing.JTextField tfEmployeeNumber;
    private javax.swing.JTextField tfFamilyName;
    private javax.swing.JTextField tfFirstName;
    private javax.swing.JPasswordField tfPassword;
    // End of variables declaration//GEN-END:variables

}
