/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * medewerkerInfo.java
 *
 * Created on 8-jan-2011, 14:25:19
 */

package view;

import java.util.Calendar;
import javax.swing.table.DefaultTableModel;
import model.Employee;
import roosterprogramma.RoosterProgramma;

/**
 *
 * @author Dark
 */
public class EmployeeInfo extends javax.swing.JPanel {

    private Employee employee;
    private DefaultTableModel model;

    /** Creates new form medewerkerInfo */
    public EmployeeInfo(Employee employee) {
        this.employee = employee;
        initComponents();
        fillInfoTable();
        fillVerantwoordingTable();
    }

    private void fillInfoTable() {
        DefaultTableModel model = (DefaultTableModel) tblEmployeeInformation.getModel();
        model.addRow(new Object[] {
            employee.getFirstName(),
            employee.getFamilyName(),
            employee.getEmployeeNumber(),
            employee.isFullTime(),
            employee.isPartTime(),
            employee.isCallWorker()
        });
    }

    private void fillVerantwoordingTable() {
        model = (DefaultTableModel) tblTimeSheet.getModel();
        Calendar calendar = Calendar.getInstance();
        int daysOfMonth = calendar.getActualMaximum(Calendar.DAY_OF_MONTH);
        for (int i = 1; i <= daysOfMonth; i++)
        {
            calendar.set(calendar.get(Calendar.YEAR), calendar.get(Calendar.MONTH)+1, i);
            model.addRow(new Object[] {
                calendar.get(Calendar.DAY_OF_MONTH),
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            });
        }
        model.addRow(new Object[] {
            "Totaal",
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        });
    }

    private void calculateTotal() {
        for (int i = 0; i < model.getRowCount(); i++)
        {
            double totalHours = 0;
            for (int j = 1; j < model.getColumnCount()-1; j++)
            {
                totalHours += Double.parseDouble(model.getValueAt(i, j).toString());
            }
            model.setValueAt(totalHours, i, model.getColumnCount()-1);
        }
        for (int k = 1; k < model.getColumnCount(); k++)
        {
            double totalHours = 0;
            for (int l = 0; l < model.getRowCount()-1; l++)
            {
                totalHours += Double.parseDouble(model.getValueAt(l, k).toString());
            }
            model.setValueAt(totalHours, model.getRowCount()-1, k);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmployeeInformation = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTimeSheet = new javax.swing.JTable();
        lblWeekNr = new javax.swing.JLabel();
        varWeekNr = new javax.swing.JLabel();
        lblVan = new javax.swing.JLabel();
        vanDatum = new javax.swing.JLabel();
        lblTot = new javax.swing.JLabel();
        totDatum = new javax.swing.JLabel();
        seperator = new javax.swing.JLabel();

        btnSave.setText("Wijzigingen opslaan");

        btnBack.setText("Vorige");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblEmployeeInformation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Voornaam", "Achternaam", "Personeelsnummer", "Fulltime", "Parttime", "Oproepkracht", "Noodhulp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblEmployeeInformation);

        tblTimeSheet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dag vd maand", "Gewerkt", "Compensatie 150", "Compensatie 200", "Vakantie", "ADV", "Ziek", "Speciaal verlof", "Project", "Totaal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTimeSheet.setRowSelectionAllowed(false);
        tblTimeSheet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tblTimeSheetKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(tblTimeSheet);

        lblWeekNr.setText("Weeknummer:");

        varWeekNr.setText("weekNr");

        lblVan.setText("Van:");

        vanDatum.setText("vanDatum");

        lblTot.setText("Tot:");

        totDatum.setText("totDatum");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1307, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1117, Short.MAX_VALUE)
                        .addComponent(btnSave))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblWeekNr)
                        .addGap(18, 18, 18)
                        .addComponent(varWeekNr)
                        .addGap(18, 18, 18)
                        .addComponent(seperator, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblVan)
                        .addGap(18, 18, 18)
                        .addComponent(vanDatum)
                        .addGap(18, 18, 18)
                        .addComponent(lblTot)
                        .addGap(18, 18, 18)
                        .addComponent(totDatum))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1307, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWeekNr)
                    .addComponent(varWeekNr)
                    .addComponent(lblVan)
                    .addComponent(vanDatum)
                    .addComponent(lblTot)
                    .addComponent(totDatum)
                    .addComponent(seperator, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnBack))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        RoosterProgramma.getInstance().showPanel(new EmployeeOverview());
    }//GEN-LAST:event_btnBackActionPerformed

    private void tblTimeSheetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblTimeSheetKeyTyped
        if (evt.getKeyChar() == '\n')
        {
            calculateTotal();
        }
    }//GEN-LAST:event_tblTimeSheetKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTot;
    private javax.swing.JLabel lblVan;
    private javax.swing.JLabel lblWeekNr;
    private javax.swing.JLabel seperator;
    private javax.swing.JTable tblEmployeeInformation;
    private javax.swing.JTable tblTimeSheet;
    private javax.swing.JLabel totDatum;
    private javax.swing.JLabel vanDatum;
    private javax.swing.JLabel varWeekNr;
    // End of variables declaration//GEN-END:variables

}
