/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Login2.java
 *
 * Created on 20-jan-2011, 11:12:42
 */

package view;

import connectivity.ShaEncrypt;
import java.awt.Color;
import model.Employee;
import roosterprogramma.RoosterProgramma;

/**
 *
 * @author Dark
 */
public class Login extends javax.swing.JPanel {

    private Employee employee;

    /** Creates new form Login2 */
    public Login(int state) {
        initComponents();
        setUpdateLabel(state);
        disablePassword();
    }

    private void setUpdateLabel(int state) {
        switch (state)
        {
            case 0:
            {
                lblUpdate.setText("U gebruikt de laatste versie van deze applicatie.");
                lblUpdate.setForeground(Color.green);
                break;
            }
            case 1:
            {
                lblUpdate.setText("U gebruikt niet de laatste versie van deze applicatie");
                lblUpdate.setForeground(Color.red);
                break;
            }
            case 2:
            {
                lblUpdate.setText("U heeft geen internetverbinding, versiecontrole is uit.");
                lblUpdate.setForeground(Color.orange);
                break;
            }
            case 3:
            {
                lblUpdate.setText("Er kan niet worden gecontroleerd op updates, een herinstallatie verhelpt dit probleem.");
                lblUpdate.setForeground(Color.orange);
                break;
            }
            default:
            {
                break;
            }
        }
    }

    private void enablePassword() {
        tfPassword.setVisible(true);
        lblPassword.setVisible(true);
        btnPasswordOk.setVisible(true);
    }

    private void disablePassword() {
        tfPassword.setVisible(false);
        lblPassword.setVisible(false);
        btnPasswordOk.setVisible(false);
    }

    private void handleName() {
        String firstName = tfFirstName.getText();
        String insertion = tfInsertion.getText();
        String familyName = tfFamilyName.getText();
        employee = RoosterProgramma.getQueryManager().getEmployee(firstName, insertion, familyName);
        if (!employee.getFirstName().isEmpty())
        {
            enablePassword();
            lblIncorrectField.setText("");
            tfPassword.requestFocusInWindow();
        }
        else
        {
            disablePassword();
            lblIncorrectField.setText("Er bestaat geen medewerker met die combinatie van voornaam en achternaam");
            tfPassword.setText("");
        }
    }

    private void handlePassword() {
        String Sha1Pass = ShaEncrypt.SHA1(RoosterProgramma.getInstance().decodePassword(tfPassword.getPassword()));
        if (Sha1Pass.equals(employee.getPassword()))
        {
            RoosterProgramma.getInstance().showPanel(new MainMenu());
        }
        else
        {
            lblIncorrectField.setText("Wachtwoord onjuist");
            tfPassword.setText("");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        familyNamePanel = new javax.swing.JPanel();
        tfFamilyName = new javax.swing.JTextField();
        btnNameOk = new javax.swing.JButton();
        lblFamilyName = new javax.swing.JLabel();
        tfFirstName = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        tfPassword = new javax.swing.JPasswordField();
        lblPassword = new javax.swing.JLabel();
        btnPasswordOk = new javax.swing.JButton();
        lblInsertion = new javax.swing.JLabel();
        tfInsertion = new javax.swing.JTextField();
        updatePanel = new javax.swing.JPanel();
        lblUpdate = new javax.swing.JLabel();
        textPanel = new javax.swing.JPanel();
        lblIncorrectField = new javax.swing.JLabel();

        tfFamilyName.setMinimumSize(new java.awt.Dimension(150, 20));
        tfFamilyName.setPreferredSize(new java.awt.Dimension(150, 20));
        tfFamilyName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfFamilyNameKeyTyped(evt);
            }
        });

        btnNameOk.setText("OK");
        btnNameOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNameOkActionPerformed(evt);
            }
        });

        lblFamilyName.setText("Achternaam   ");

        tfFirstName.setPreferredSize(new java.awt.Dimension(150, 20));
        tfFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfFirstNameKeyTyped(evt);
            }
        });

        lblFirstName.setText("Voornaam");

        tfPassword.setPreferredSize(new java.awt.Dimension(150, 20));
        tfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPasswordKeyTyped(evt);
            }
        });

        lblPassword.setText("Wachtwoord");

        btnPasswordOk.setText("OK");
        btnPasswordOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasswordOkActionPerformed(evt);
            }
        });

        lblInsertion.setText("Tussenvoegsel");

        tfInsertion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfInsertionKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout familyNamePanelLayout = new javax.swing.GroupLayout(familyNamePanel);
        familyNamePanel.setLayout(familyNamePanelLayout);
        familyNamePanelLayout.setHorizontalGroup(
            familyNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(familyNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(familyNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInsertion)
                    .addComponent(lblFirstName)
                    .addComponent(lblFamilyName)
                    .addComponent(lblPassword))
                .addGap(18, 18, 18)
                .addGroup(familyNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(familyNamePanelLayout.createSequentialGroup()
                        .addGroup(familyNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfInsertion, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                            .addComponent(tfFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                            .addComponent(tfFamilyName, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnNameOk))
                    .addGroup(familyNamePanelLayout.createSequentialGroup()
                        .addComponent(tfPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPasswordOk)))
                .addContainerGap())
        );
        familyNamePanelLayout.setVerticalGroup(
            familyNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(familyNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(familyNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFirstName)
                    .addComponent(tfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(familyNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInsertion)
                    .addComponent(tfInsertion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(familyNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFamilyName)
                    .addComponent(btnNameOk)
                    .addComponent(tfFamilyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(familyNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPasswordOk))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        updatePanel.add(lblUpdate);

        textPanel.add(lblIncorrectField);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(familyNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(updatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(familyNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(textPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(mainPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void tfFirstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFirstNameKeyTyped
        if (evt.getKeyChar() == '\n')
        {
            tfInsertion.requestFocusInWindow();
        }
    }//GEN-LAST:event_tfFirstNameKeyTyped

    private void tfPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPasswordKeyTyped
        if (evt.getKeyChar() == '\n')
        {
            handlePassword();
        }
    }//GEN-LAST:event_tfPasswordKeyTyped

    private void btnNameOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNameOkActionPerformed
        handleName();
    }//GEN-LAST:event_btnNameOkActionPerformed

    private void btnPasswordOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasswordOkActionPerformed
        handlePassword();
    }//GEN-LAST:event_btnPasswordOkActionPerformed

    private void tfFamilyNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFamilyNameKeyTyped
        if (evt.getKeyChar() == '\n')
        {
            handleName();
        }
    }//GEN-LAST:event_tfFamilyNameKeyTyped

    private void tfInsertionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfInsertionKeyReleased
        if (evt.getKeyChar() == '\n')
        {
            tfFamilyName.requestFocusInWindow();
        }
}//GEN-LAST:event_tfInsertionKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNameOk;
    private javax.swing.JButton btnPasswordOk;
    private javax.swing.JPanel familyNamePanel;
    private javax.swing.JLabel lblFamilyName;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblIncorrectField;
    private javax.swing.JLabel lblInsertion;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUpdate;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel textPanel;
    private javax.swing.JTextField tfFamilyName;
    private javax.swing.JTextField tfFirstName;
    private javax.swing.JTextField tfInsertion;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JPanel updatePanel;
    // End of variables declaration//GEN-END:variables
}