/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * medewerkerInfo.java
 *
 * Created on 8-jan-2011, 14:25:19
 */

package view;

import javax.swing.table.DefaultTableModel;
import model.Employee;
import model.EmployeeInfo;
import roosterprogramma.RoosterProgramma;

/**
 *
 * @author Dark
 */
public class medewerkerInfo extends javax.swing.JPanel {

    private Employee werknemer;

    /** Creates new form medewerkerInfo */
    public medewerkerInfo(int medewerkerID) {
        this.werknemer = RoosterProgramma.getQueryManager().getEmployee(medewerkerID);
        initComponents();
        fillInfoTable();
        //fillWerktijdenInfoTable(); //tijdelijk weggecomment, werkt nog niet.
        fillVerantwoordingTable();
    }

    private void fillInfoTable() {
        DefaultTableModel model = (DefaultTableModel) werknemerInfo.getModel();
        //  Algmene werknemer info
        model.addRow(new Object[] {
            werknemer.getVoornaam(),
            werknemer.getAchternaam(),
            werknemer.getPersoneelsNummer(),
            werknemer.isFulltime(),
            werknemer.isParttime(),
            werknemer.isOproepkracht()
        });
    }

    private void fillWerktijdenInfoTable() {
        DefaultTableModel model = (DefaultTableModel) werktijdenInfo.getModel();
        model.addRow(new Object[] {
            werknemer.getMaandag().getContracturen(),
            werknemer.getDinsdag().getContracturen(),
            werknemer.getWoensdag().getContracturen(),
            werknemer.getDonderdag().getContracturen(),
            werknemer.getVrijdag().getContracturen(),
            werknemer.getZaterdag().getContracturen(),
            werknemer.getZondag().getContracturen()
        });
    }

    private void fillVerantwoordingTable() {
        DefaultTableModel model = (DefaultTableModel) urenVerantwoording.getModel();
        model.addRow(new Object[] {
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        werktijdenInfo = new javax.swing.JTable();
        Opslaan = new javax.swing.JButton();
        Vorige = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        werknemerInfo = new javax.swing.JTable();
        emptySpace = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        urenVerantwoording = new javax.swing.JTable();
        lblWeekNr = new javax.swing.JLabel();
        weekNr = new javax.swing.JLabel();
        lblVan = new javax.swing.JLabel();
        vanDatum = new javax.swing.JLabel();
        lblTot = new javax.swing.JLabel();
        totDatum = new javax.swing.JLabel();
        seperator = new javax.swing.JLabel();

        werktijdenInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Contracturen", new Integer(0), new Integer(0), new Integer(0), new Integer(0), new Integer(0), new Integer(0), new Integer(0), new Integer(0)},
                {"Te werken", new Integer(0), new Integer(0), new Integer(0), new Integer(0), new Integer(0), new Integer(0), new Integer(0), new Integer(0)}
            },
            new String [] {
                "", "Ma", "Di", "Wo", "Do", "Vr", "Za", "Zo", "Totaal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(werktijdenInfo);

        Opslaan.setText("Wijzigingen opslaan");

        Vorige.setText("Vorige");
        Vorige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VorigeActionPerformed(evt);
            }
        });

        werknemerInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", null, new Boolean(false), null, null, new Boolean(false)}
            },
            new String [] {
                "Voornaam", "Achternaam", "Personeelsnummer", "Fulltime", "Parttime", "Oproepkracht", "Noodhulp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(werknemerInfo);

        javax.swing.GroupLayout emptySpaceLayout = new javax.swing.GroupLayout(emptySpace);
        emptySpace.setLayout(emptySpaceLayout);
        emptySpaceLayout.setHorizontalGroup(
            emptySpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1307, Short.MAX_VALUE)
        );
        emptySpaceLayout.setVerticalGroup(
            emptySpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        urenVerantwoording.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Werkelijk gewerkt", null, null, null, null, null, null, null, null},
                {"Meer gewerkt te betalen", null, null, null, null, null, null, null, null},
                {"Meer gewerkt te compenseren", null, null, null, null, null, null, null, null},
                {"Minder gewerkt", null, null, null, null, null, null, null, null},
                {"ATV", null, null, null, null, null, null, null, null},
                {"Vakantie", null, null, null, null, null, null, null, null},
                {"Compensatie 33.33%", null, null, null, null, null, null, null, null},
                {"Compensatie 50%", null, null, null, null, null, null, null, null},
                {"Compensatie 100%", null, null, null, null, null, null, null, null},
                {"Doktersbezoek", null, null, null, null, null, null, null, null},
                {"Ziekte", null, null, null, null, null, null, null, null},
                {"Niet gewerkt eigen rekenening", null, null, null, null, null, null, null, null},
                {"Feestdagen", null, null, null, null, null, null, null, null},
                {"Compensatie Opname", null, null, null, null, null, null, null, null},
                {"CAO Verlof", null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "Ma", "Di", "Wo", "Do", "Vr", "Za", "Zo", "Totaal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(urenVerantwoording);

        lblWeekNr.setText("Weeknummer:");

        weekNr.setText("weekNr");

        lblVan.setText("Van:");

        vanDatum.setText("vanDatum");

        lblTot.setText("Tot:");

        totDatum.setText("totDatum");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(emptySpace, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(Vorige)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1117, Short.MAX_VALUE)
                        .addComponent(Opslaan))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblWeekNr)
                        .addGap(18, 18, 18)
                        .addComponent(weekNr)
                        .addGap(18, 18, 18)
                        .addComponent(seperator, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblVan)
                        .addGap(18, 18, 18)
                        .addComponent(vanDatum)
                        .addGap(18, 18, 18)
                        .addComponent(lblTot)
                        .addGap(18, 18, 18)
                        .addComponent(totDatum))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1307, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1307, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1307, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWeekNr)
                    .addComponent(weekNr)
                    .addComponent(lblVan)
                    .addComponent(vanDatum)
                    .addComponent(lblTot)
                    .addComponent(totDatum)
                    .addComponent(seperator, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emptySpace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Opslaan)
                    .addComponent(Vorige))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void VorigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VorigeActionPerformed
        RoosterProgramma.getInstance().showPanel(new medewerkerOverzicht());
    }//GEN-LAST:event_VorigeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Opslaan;
    private javax.swing.JButton Vorige;
    private javax.swing.JPanel emptySpace;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTot;
    private javax.swing.JLabel lblVan;
    private javax.swing.JLabel lblWeekNr;
    private javax.swing.JLabel seperator;
    private javax.swing.JLabel totDatum;
    private javax.swing.JTable urenVerantwoording;
    private javax.swing.JLabel vanDatum;
    private javax.swing.JLabel weekNr;
    private javax.swing.JTable werknemerInfo;
    private javax.swing.JTable werktijdenInfo;
    // End of variables declaration//GEN-END:variables

}
