/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * medewerkerInfo.java
 *
 * Created on 8-jan-2011, 14:25:19
 */

package view;

import javax.swing.table.DefaultTableModel;
import model.Employee;
import model.EmployeeInfo;
import roosterprogramma.RoosterProgramma;

/**
 *
 * @author Dark
 */
public class MedewerkerInfo extends javax.swing.JPanel {

    private Employee employee;

    /** Creates new form medewerkerInfo */
    public MedewerkerInfo(Employee employee) {
        this.employee = employee;
        initComponents();
        fillInfoTable();
        //fillWerktijdenInfoTable(); //tijdelijk weggecomment, werkt nog niet.
        fillVerantwoordingTable();
    }

    private void fillInfoTable() {
        DefaultTableModel model = (DefaultTableModel) tblEmployeeInformation.getModel();
        //  Algmene werknemer info
        model.addRow(new Object[] {
            employee.getVoornaam(),
            employee.getAchternaam(),
            employee.getPersoneelsNummer(),
            employee.isFulltime(),
            employee.isParttime(),
            employee.isOproepkracht()
        });
    }

    private void fillWerktijdenInfoTable() {
        DefaultTableModel model = (DefaultTableModel) tblHours.getModel();
        model.addRow(new Object[] {
            employee.getMaandag().getContracturen(),
            employee.getDinsdag().getContracturen(),
            employee.getWoensdag().getContracturen(),
            employee.getDonderdag().getContracturen(),
            employee.getVrijdag().getContracturen(),
            employee.getZaterdag().getContracturen(),
            employee.getZondag().getContracturen()
        });
    }

    private void fillVerantwoordingTable() {
        DefaultTableModel model = (DefaultTableModel) tblTimeSheets.getModel();
        model.addRow(new Object[] {
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblHours = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmployeeInformation = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTimeSheets = new javax.swing.JTable();
        lblWeekNr = new javax.swing.JLabel();
        varWeekNr = new javax.swing.JLabel();
        lblVan = new javax.swing.JLabel();
        vanDatum = new javax.swing.JLabel();
        lblTot = new javax.swing.JLabel();
        totDatum = new javax.swing.JLabel();
        seperator = new javax.swing.JLabel();

        tblHours.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Contracturen", new Integer(0), new Integer(0), new Integer(0), new Integer(0), new Integer(0), new Integer(0), new Integer(0), new Integer(0)},
                {"Te werken", new Integer(0), new Integer(0), new Integer(0), new Integer(0), new Integer(0), new Integer(0), new Integer(0), new Integer(0)}
            },
            new String [] {
                "", "Ma", "Di", "Wo", "Do", "Vr", "Za", "Zo", "Totaal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHours);

        btnSave.setText("Wijzigingen opslaan");

        btnBack.setText("Vorige");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblEmployeeInformation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", null, new Boolean(false), null, null, new Boolean(false)}
            },
            new String [] {
                "Voornaam", "Achternaam", "Personeelsnummer", "Fulltime", "Parttime", "Oproepkracht", "Noodhulp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblEmployeeInformation);

        tblTimeSheets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Werkelijk gewerkt", null, null, null, null, null, null, null, null},
                {"Meer gewerkt te betalen", null, null, null, null, null, null, null, null},
                {"Meer gewerkt te compenseren", null, null, null, null, null, null, null, null},
                {"Minder gewerkt", null, null, null, null, null, null, null, null},
                {"ATV", null, null, null, null, null, null, null, null},
                {"Vakantie", null, null, null, null, null, null, null, null},
                {"Compensatie 33.33%", null, null, null, null, null, null, null, null},
                {"Compensatie 50%", null, null, null, null, null, null, null, null},
                {"Compensatie 100%", null, null, null, null, null, null, null, null},
                {"Doktersbezoek", null, null, null, null, null, null, null, null},
                {"Ziekte", null, null, null, null, null, null, null, null},
                {"Niet gewerkt eigen rekenening", null, null, null, null, null, null, null, null},
                {"Feestdagen", null, null, null, null, null, null, null, null},
                {"Compensatie Opname", null, null, null, null, null, null, null, null},
                {"CAO Verlof", null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "Ma", "Di", "Wo", "Do", "Vr", "Za", "Zo", "Totaal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblTimeSheets);

        lblWeekNr.setText("Weeknummer:");

        varWeekNr.setText("weekNr");

        lblVan.setText("Van:");

        vanDatum.setText("vanDatum");

        lblTot.setText("Tot:");

        totDatum.setText("totDatum");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1117, Short.MAX_VALUE)
                        .addComponent(btnSave))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblWeekNr)
                        .addGap(18, 18, 18)
                        .addComponent(varWeekNr)
                        .addGap(18, 18, 18)
                        .addComponent(seperator, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblVan)
                        .addGap(18, 18, 18)
                        .addComponent(vanDatum)
                        .addGap(18, 18, 18)
                        .addComponent(lblTot)
                        .addGap(18, 18, 18)
                        .addComponent(totDatum))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1307, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1307, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1307, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWeekNr)
                    .addComponent(varWeekNr)
                    .addComponent(lblVan)
                    .addComponent(vanDatum)
                    .addComponent(lblTot)
                    .addComponent(totDatum)
                    .addComponent(seperator, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnBack))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        RoosterProgramma.getInstance().showPanel(new MedewerkerOverzicht());
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTot;
    private javax.swing.JLabel lblVan;
    private javax.swing.JLabel lblWeekNr;
    private javax.swing.JLabel seperator;
    private javax.swing.JTable tblEmployeeInformation;
    private javax.swing.JTable tblHours;
    private javax.swing.JTable tblTimeSheets;
    private javax.swing.JLabel totDatum;
    private javax.swing.JLabel vanDatum;
    private javax.swing.JLabel varWeekNr;
    // End of variables declaration//GEN-END:variables

}
