/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SettingsMenu.java
 *
 * Created on 30-jan-2011, 19:00:36
 */

package view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JTextField;
import roosterprogramma.RoosterProgramma;

/**
 *
 * @author Dark
 */
public class SettingsMenu extends javax.swing.JPanel {

    private List<JTextField> fields = new ArrayList<JTextField>();

    /** Creates new form SettingsMenu */
    public SettingsMenu() {
        initComponents();
        fillFields();
    }

    private void fillFields() {
        // ToDo : Vullen met database info
        tfX1.setText("");
        tfX1till.setText("");
        tfX2.setText("");
        tfX2till.setText("");
        tfX3.setText("");
        tfX3till.setText("");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFlowLayout = new javax.swing.JPanel();
        pnlBoxLayout = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfX1 = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        tfX1till = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfX2 = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        tfX2till = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfX3 = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        tfX3till = new javax.swing.JFormattedTextField();
        lblSettings = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();

        pnlBoxLayout.setLayout(new javax.swing.BoxLayout(pnlBoxLayout, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("X1 : ");
        jPanel1.add(jLabel1);

        tfX1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        tfX1.setPreferredSize(new java.awt.Dimension(50, 20));
        tfX1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfX1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfX1KeyReleased(evt);
            }
        });
        jPanel1.add(tfX1);

        jLabel4.setText(" Tot ");
        jPanel1.add(jLabel4);

        tfX1till.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        tfX1till.setPreferredSize(new java.awt.Dimension(50, 20));
        tfX1till.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfX1tillKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfX1tillKeyReleased(evt);
            }
        });
        jPanel1.add(tfX1till);

        pnlBoxLayout.add(jPanel1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("X2 : ");
        jPanel2.add(jLabel2);

        tfX2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        tfX2.setPreferredSize(new java.awt.Dimension(50, 20));
        tfX2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfX2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfX2KeyReleased(evt);
            }
        });
        jPanel2.add(tfX2);

        jLabel5.setText(" Tot ");
        jPanel2.add(jLabel5);

        tfX2till.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        tfX2till.setPreferredSize(new java.awt.Dimension(50, 20));
        tfX2till.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfX2tillKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfX2tillKeyReleased(evt);
            }
        });
        jPanel2.add(tfX2till);

        pnlBoxLayout.add(jPanel2);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setText("X3 : ");
        jPanel3.add(jLabel3);

        tfX3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        tfX3.setPreferredSize(new java.awt.Dimension(50, 20));
        tfX3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfX3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfX3KeyReleased(evt);
            }
        });
        jPanel3.add(tfX3);

        jLabel6.setText(" Tot ");
        jPanel3.add(jLabel6);

        tfX3till.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        tfX3till.setPreferredSize(new java.awt.Dimension(50, 20));
        tfX3till.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfX3tillKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfX3tillKeyReleased(evt);
            }
        });
        jPanel3.add(tfX3till);

        pnlBoxLayout.add(jPanel3);

        pnlFlowLayout.add(pnlBoxLayout);

        lblSettings.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblSettings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSettings.setText("Instellingen");

        btnSave.setText("Opslaan");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnPrevious.setText("Terug");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlFlowLayout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                    .addComponent(lblSettings, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrevious)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 611, Short.MAX_VALUE)
                        .addComponent(btnSave)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblSettings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFlowLayout, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnPrevious))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfX1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfX1KeyReleased
        handleTextField(tfX1);
        checkEnabled();
    }//GEN-LAST:event_tfX1KeyReleased

    private void tfX2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfX2KeyReleased
        handleTextField(tfX2);
        checkEnabled();
    }//GEN-LAST:event_tfX2KeyReleased

    private void tfX3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfX3KeyReleased
        handleTextField(tfX3);
        checkEnabled();
    }//GEN-LAST:event_tfX3KeyReleased

    private void tfX1tillKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfX1tillKeyReleased
        handleTextField(tfX1till);
        checkEnabled();
    }//GEN-LAST:event_tfX1tillKeyReleased

    private void tfX2tillKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfX2tillKeyReleased
        handleTextField(tfX2till);
        checkEnabled();
    }//GEN-LAST:event_tfX2tillKeyReleased

    private void tfX3tillKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfX3tillKeyReleased
        handleTextField(tfX3till);
        checkEnabled();
    }//GEN-LAST:event_tfX3tillKeyReleased

    private void tfX1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfX1KeyPressed
        handleTextField(tfX1);
    }//GEN-LAST:event_tfX1KeyPressed

    private void tfX2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfX2KeyPressed
        handleTextField(tfX2);
    }//GEN-LAST:event_tfX2KeyPressed

    private void tfX3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfX3KeyPressed
        handleTextField(tfX3);
    }//GEN-LAST:event_tfX3KeyPressed

    private void tfX1tillKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfX1tillKeyPressed
        handleTextField(tfX1till);
    }//GEN-LAST:event_tfX1tillKeyPressed

    private void tfX2tillKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfX2tillKeyPressed
        handleTextField(tfX2till);
    }//GEN-LAST:event_tfX2tillKeyPressed

    private void tfX3tillKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfX3tillKeyPressed
        handleTextField(tfX3till);
    }//GEN-LAST:event_tfX3tillKeyPressed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        RoosterProgramma.getInstance().showPanel(new MainMenu());
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // ToDo : In de database stoppen (eerst dus een Query maken)
    }//GEN-LAST:event_btnSaveActionPerformed

    private void handleTextField(JTextField field) {
        if (field.getText().length() == 2)
        {
            field.setText(field.getText() + ":");
        }
        else if (field.getText().length() > 5)
        {
            field.setText(field.getText().substring(0, 5));
        }
    }

    private void checkEnabled() {
        int correct = 0;
        for(JTextField field : fields)
        {
            if(isCorrect(field))
            {
                correct += 1;
            }
        }

        if (correct == fields.size())
        {
            btnSave.setEnabled(true);
        }
        else
        {
            btnSave.setEnabled(false);
        }
    }

    private boolean isCorrect(JTextField field) {
        boolean correct = false;
        if (field.getText().length() == 5)
        {
            String[] pieces = field.getText().split(":");
            if (RoosterProgramma.getInstance().isNumeric(pieces[0]) && RoosterProgramma.getInstance().isNumeric(pieces[1]))
            {
                correct = true;
            }
        }
        return correct;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblSettings;
    private javax.swing.JPanel pnlBoxLayout;
    private javax.swing.JPanel pnlFlowLayout;
    private javax.swing.JFormattedTextField tfX1;
    private javax.swing.JFormattedTextField tfX1till;
    private javax.swing.JFormattedTextField tfX2;
    private javax.swing.JFormattedTextField tfX2till;
    private javax.swing.JFormattedTextField tfX3;
    private javax.swing.JFormattedTextField tfX3till;
    // End of variables declaration//GEN-END:variables

}
